services:

  dc1:
    container_name: ${DC_NAME}
    hostname: ${DC_NAME}
    build:
      context: ./samba/dockerfile
      target: dc
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./samba/config-dc1:/etc/samba/config
      - ./samba/data-dc1:/var/lib/samba
      - ./authorized_keys:/root/.ssh/authorized_keys:ro
    environment:
      - DOMAIN_FQDN=${DOMAIN_FQDN}
      - DOMAIN_DN=${DOMAIN_DN}
      - DNSFORWARDER=${MAIN_DNS_IP}
      - DC_IP=${DC_IP}
    dns_search:
      - ${DOMAIN_FQDN}
    dns:
      - ${DC_IP}
      - ${MAIN_DNS_IP}
    extra_hosts:
      - ${DC_NAME}.${DOMAIN_FQDN}:${DC_IP}
    privileged: true                                  # Run as true root. Required by Samba because it uses the security.* namespace (see https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html).
    networks:
      sambanet:
        ipv4_address: ${DC_IP}

  fs1:
    container_name: ${FS_NAME}
    hostname: ${FS_NAME}
    build:
      context: ./samba/dockerfile
      target: fs
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./samba/config-fs1/samba:/etc/samba/config
      - ./samba/config-fs1/supervisor:/etc/supervisor/config:ro
      - ./samba/data-fs1:/var/lib/samba
      - ./samba/shares-fs1:/srv/samba
      - ./authorized_keys:/root/.ssh/authorized_keys:ro
    environment:
      - DOMAIN_FQDN=${DOMAIN_FQDN}
      - DOMAIN_DN=${DOMAIN_DN}
      - FS_NAME=${FS_NAME}
      - FS_IP=${FS_IP}
    dns_search:
      - ${DOMAIN_FQDN}
    dns:
      - ${MAIN_DNS_IP}
    extra_hosts:
      - ${FS_NAME}.${DOMAIN_FQDN}:${FS_IP}
    privileged: true                                  # Run as true root. Required by Samba because it uses the security.* namespace (see https://www.samba.org/samba/docs/current/man-html/vfs_acl_xattr.8.html).
    networks:
      sambanet:
        ipv4_address: ${FS_IP}
    depends_on:
      - dc1

networks:
  sambanet:
    name: ${DOCKER_NETWORK_NAME}
    driver: macvlan
    driver_opts:
      parent: ${HOST_INTERFACE}
    ipam:
      config:
        - subnet: "${SUBNET}"                         # Shared with the host
          gateway: "${GATEWAY}"                       # Same as on the host
          ip_range: "${CONTAINER_IP_RANGE}"           # Tell Docker which IP addresses are available for containers
#          aux_addresses:                              # Inform Docker about addresses already in use
#            host: ${MAIN_DNS_IP}